version: "2.2"

services:
  mysql:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=sidecar
      - MYSQL_PASSWORD=sidecar
      - MYSQL_DATABASE=sidecar
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana    
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=redis-app

  redis:
    image: redis/redis-stack-server
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
      
  redis-sidecar-demo:
    image: fieldengineering/redis-sidecar-demo
    hostname: sidecar-demo
    container_name: sidecar-demo
    build: .
    restart: on-failure
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/sidecar