version: "2.2"

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=smartcache
      - MYSQL_PASSWORD=smartcache
      - MYSQL_DATABASE=smartcache

  grafana:
    image: smartcache/grafana
    build:
      context: ./docker/grafana
      dockerfile: ./Dockerfile
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000

  redis:
    image: redis-server-with-cache-cli
    build:
      context: ./docker/redis
      dockerfile: ./Dockerfile
    hostname: redis
    container_name: redis-server-with-cache-cli
    ports:
      - 6379:6379
      
  redis-cache:
    image: redis:7.0.12
    hostname: redis-cache
    container_name: redis-cache
    ports:
      - 6380:6379
