version: "2.2"

services:
  mysql:
    image: mysql:latest
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=smartcache
      - MYSQL_PASSWORD=smartcache
      - MYSQL_DATABASE=smartcache
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"

  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=redis-app

  redis:
    image: redis/redis-stack-server
    hostname: redis
    ports:
      - 6379:6379
      
  redis-smart-cache-demo:
    image: fieldengineering/redis-demo-smart-cache
    hostname: smartcache
    build: .
    restart: on-failure
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/smartcache