name: 'Benchmark'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        default: 'master'
        required: false

jobs:
  benchmark:
    name: Benchmark
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/benchmark.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      jmh-results-path: core/redis-smart-cache-test/build/results/jmh/results.txt
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}